
# Header
menu:
  主页: /hexoblog
  归档: /hexoblog/archives
  关于: /hexoblog/2000/01/01/about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
#google_analytics:
favicon: /hexoblog/img/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id: